### ISSUE TITLE
Request: Sync NTP time with Powermax time at any event

### ISSUE THREAD

**Issue by Element2** [ayasystems/PowerMaxEsp8266#6]
Although the ESP syncs the time by NTP, the system time of the Powermax -panel isn't.
It would be nice if at any arbitrary moment, but at least once a day, the Powermax system time would be synced with the ESP time.
Maybe this could be done when any kind of event is fired.
As far as I can see the pmax lib has a function for setting the time. 
I would try this myself, but I can't get the source compiled due to a lot of compiling errors.

**Comment by ayasystems** [comment]
If you can not compile it check the libraries.... 

Update powermax date/time from esp8266 was not implemented, i'm sorry

**Comment by Element2** [comment]
Wow, thanks for the update!
Can you publish a new compiled version pretty please?
